name: Sync to S3 & Invalidate Cloudfront
run-name: Sync and Deploy
on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@master
      - run: yarn install
      - run: yarn build
      - run: ls -al ./out
      - uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          SOURCE_DIR: ${{ vars.SOURCE_DIR }}
          DEST_DIR: ${{ vars.DEST_DIR }}

  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS: "/*"
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
