name: Sync to S3 & Invalidate Cloudfront
run-name: Sync and Deploy
on:
  push:
    branches: ["master"]
    paths:
      - '**.tsx'
      - 'public/**'
      - '**.scss'

jobs:
  build:
    name: Build static files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check versions
        run: |
          echo "Commit $(git show --oneline -s)"
          echo "node version $(node --version)"
          echo "npm version $(npm --version)"
          echo "yarn version $(yarn --version)"

      - name: Run build
        run: |
          yarn install
          yarn build
          ls -al ./out

      - name: Build output artifact
        uses: actions/upload-artifact@v4
        with:
          name: static-build
          path: ./out
          overwrite: true

  sync:
    name: S3 sync
    needs: build
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: static-build
          path: ./out
          overwrite: true

      - name: Sync to S3
        uses: raulanatol/aws-s3-docker-action@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET }}
          SOURCE: "./out"
          TARGET: ""

  deploy:
    name: Cloudfront invalidation
    needs: sync
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Invalidate CloudFront distro
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS: "/*"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
